"""add order model

Revision ID: d8ceda7bb033
Revises: 
Create Date: 2020-09-05 14:16:09.253236+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ceda7bb033'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', name='ordertype'), nullable=False),
    sa.Column('order_side', sa.Enum('ASK', 'BID', name='ordersidetype'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=36, scale=18), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=36, scale=18), nullable=True),
    sa.Column('status', sa.Enum('EXECUTED', 'OPEN', 'PARTIALLY_FILLED', 'CANCELED', name='orderstatuetype'), nullable=True),
    sa.Column('filled_size', sa.DECIMAL(precision=36, scale=18), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
